return {
  -- You can also add new plugins here as well:
  -- Add plugins, the lazy syntax
  -- "andweeb/presence.nvim",
  -- {
  --   "ray-x/lsp_signature.nvim",
  --   event = "BufRead",
  --   config = function()
  --     require("lsp_signature").setup()
  --   end,
  -- },
  -- {
  --   "leoluz/nvim-dap-go",
  --   config = function()
  --     require("dap-go").setup {
  --       -- delve = {},
  --       dap_configurations = {
  --         type = "go",
  --         name = "klikit serve",
  --         request = "launch",
  --         mode = "auto",
  --         program = "${workspaceFolder}",
  --         args = {"serve"},
  --         -- dlvFlags = 
  --         -- env = 
  --       },
  --     }
  --   end,
  -- },
}
